spring:
  application:
    name: EventHub

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/EventHubDB
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: dimon.2007.17@gmail.com
    password: hlcp iesn abmu owrv
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs-json

jwt:
  secret-key: NeRealSecretKeyForFreaksAniMeTrackAPIAndAniMeTrackAPP
  expiration-time: 86400000

app:
  base-url: http://localhost:8080
  email:
    from: dimon.2007.17@gmail.com
    sender-name: EventHub


